config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  
  resources :users, only: [:show, :new, :create] 
  
  resources :books, only: [:show, :new]
  
  resources :ownerships, only: [:create, :destroy]
  
  get 'rankings/want', to: 'rankings#want'
  get 'rankings/have', to: 'rankings#have'
  get 'rankings/review', to: 'rankings#review'
  
  resources :reviews, only: [:create, :destroy]
  
  resources :my_conditions do
    get 'cities_select', on: :collection
  end

end

app/models/book.rb
class Book < ApplicationRecord
  validates :isbn, presence: true, length: { maximum: 13 }
  validates :title, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
  
  has_many :ownerships
  has_many :users, through: :ownerships
  has_many :wants
  has_many :want_users, through: :wants, class_name: 'User', source: :user
  has_many :haves, class_name: 'Have'
  has_many :have_users, through: :haves, class_name: 'User', source: :user
  has_many :reviews
  has_many :review_users, through: :reviews, class_name: 'User', source: :user

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
    @books = []
    @title = params[:title]
    
    if @title.present?
      results = RakutenWebService::Books::Book.search({
        title: @title,
        hits: 20,
        booksGenreId: '001005'
      })
      
      results.each do |result|
        book = Book.find_or_initialize_by(read(result))
        @books << book
      end
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @want_users = @book.want_users
    @have_users = @book.have_users
    @review_users = @book.review_users
    @book_reviews = @book.reviews
    @book_rating_average = Review.book_average(params[:id]).to_f.to_s;
    
    if current_user  
      # ユーザの検索条件取得
      @my_conditions = MyCondition.where(user_id: current_user.id)
      # システムIDの配列を生成
      conditions_systemid = @my_conditions.pluck("systemid_for_calil")
      
      # 蔵書検索
      @calil_books = Calil::Book.find([@book["isbn"]], conditions_systemid).first
    end 
  end
end

app/views/books/_book_search.html.erb
<div class="cover">
  <div class="cover-inner">
    <div class="cover-contents">
      <h1 class="site-logo"><img src="/images/logo.png" alt="HackTechBook"></h1>
      <div class="search">
        <div class="row">
          <div class="text-center">
            <%= form_tag(new_book_path, method: :get, class: 'form-inline form-search') do %>
                  <%= text_field_tag :title, @title, class: 'form-control input-lg input-search', placeholder: "たのしいRuby", size: 50, minlength: 2 %>
                  <%= button_tag type: 'submit', class: 'btn input-lg btn-search' do %>
                    <i class="fa fa-search"></i>
                  <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/_books.html.erb
<% if books %>
  <div class="row">
    <% books.each do |book| %>
      <div class="book">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= book.image_url %>" alt="" >
            </div>
            <div class="panel-body">
              <% if book.persisted? %>
                <p class="book-title"><%= link_to book.title, book %></p>
              <% else %>
                <p class="book-title"><%= book.title %></p>
              <% end %>
              <div class="buttons text-center">
                <% if logged_in? %>
                  <%= render 'ownerships/want_button', book: book %>
                  <%= render 'ownerships/have_button', book: book %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/new.html.erb
<%= render 'books', books: @books %>

app/views/books/show.html.erb
<script>
$(function(){
  
    $('.set_star').raty( {
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf : '<%= asset_path('star-half.png') %>',
    readOnly: true,   //閲覧者によるスコアの変更不可  
    score: function() {
      return $(this).attr('data-score');
    }
  });
  
  $('.star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    scoreName: 'reviews[rating]' 
  });
  
  $('.js-review-button').on('click', function(){
    $('.js-review-writing').toggleClass('hidden');
  });
  
   $('.js-review_users-info').click(function() {
      // スクロールの速度
      var speed = 400; // ミリ秒
      // アンカーの値取得
      var href= $(this).attr("href");
      // 移動先を取得
      var target = $(href == "#" || href == "" ? 'html' : href);
      // 移動先を数値で取得
      var position = target.offset().top;
      // スムーススクロール
      $('body,html').animate({scrollTop:position}, speed, 'swing');
      return false;
   });
  
});
</script>

<div class="row">
  <div class="col-md-1" style="text-align:left;padding-top:5px">
    <%= link_to '前に戻る', current_user ? user_path(current_user) : root_path %> 
  </div>
  
  <div class="col-md-10">
    <div class="col-md-5 book-image-wrap">
      <div class="book">
        <img src="<%= @book.image_url %>" alt="" class="book-image">
        <p><%= link_to "楽天詳細ページへ  ¥#{@book.price.to_i.to_s(:delimited)}より", @book.url, target: '_blank', class: "btn btn-default link-rakuten" %></p>
      </div>
    </div>
    <div class="col-md-7 book-detail-wrap">
      <h2 class="book-title"><%= @book.title %></h2>
      <p class="book-author"><i class="fa fa-user" style="color:#999"></i><%= @book.author %></p>
      <div class="book-info-area">
        <div class="rating-area">
          <ul class="list-inline">
            <li class="set_star" data-score="<%= @book_rating_average %>"></li>
            <li><a href="#reviews-area" class="js-review_users-info"><%= @review_users.count %>件のレビュー</a></li>
          </ul>
        </div>
        <div class="ownership-area">
          <ul class="list-inline">
            <li><%= @want_users.count %> 欲しい！</li>
            <li><%= @have_users.count %> 持ってる！</li>
            <li><%= render 'ownerships/want_button', book: @book %></li>
            <li><%= render 'ownerships/have_button', book: @book %></li>
          </ul>
        </div>
        <div class="review-writing-area">
          <div class="js-review">
            <div class="js-review-button btn btn-small btn-default">
            <i class="fa fa-edit"></i>レビューを書く</div>
          </div>
          <div class="js-review-writing hidden">
            <hr>
            <%= form_for(:reviews, url: reviews_path, method: :post, id: 'js-review-form') do |f| %>
              <p>この本の評価：<span class="star"></span></p>
              <%= f.hidden_field :book_id, value: @book.id %>
              <div class="form-group">
                <%= f.text_area :review, class: 'form-control', rows: '5', required: true %>
              </div>
              <div class="text-right">
                <%= f.submit '保存する', class: 'btn btn-primary' %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="caption-area">
          <div class="panel panel-default">
            <div class="panel-heading">商品説明</div>
            <div class="panel-body"><%= @book.caption.present? ? @book.caption : '記載なし' %></div>
          </div>
        </div>
        <div class="calil_area">
            <div class="panel panel-default">
              <div class="panel-heading">蔵書検索</div>
              <% if @calil_books.present? && @my_conditions.present? %>
                <% @calil_books.systems.each do |calil_book| %>
                  <div class="panel-body">
                    <ul class="list-inline">
                      <li><%= @my_conditions.find {|condition| condition["systemid_for_calil"] == calil_book.systemid}.systemname_for_calil %></li>
                      <% if calil_book.reservable? %>
                        <li><%= link_to '蔵書あり', calil_book.reserveurl, target: "_blank", class: 'btn btn-warning btn-sm' %></li>
                      <% else %>
                        <li>蔵書なし</li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
              <% else %>
                <div class="panel-body">
                  <%= link_to '検索地域を設定する', my_conditions_path %>
                </div>
              <% end %>
              <div class="text-right calil_banner">
                <span>by </span><%= link_to image_tag('/images/calil_banner.gif'), "https://calil.jp/book/#{@book.isbn}", target: "_blank" %>
              </div>
            </div>
        </div>
        <div id="reviews-area" class="reviews-area">
          <%= render 'reviews/book_reviews', book_reviews: @book_reviews if @book_reviews.count > 0 %>
        </div>
      </div>
    </div>
  </div>
</div>