config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  
  resources :users, only: [:show, :new, :create] 
  
  resources :books, only: [:show, :new]
  
  resources :ownerships, only: [:create, :destroy]
  
  get 'rankings/want', to: 'rankings#want'
  get 'rankings/have', to: 'rankings#have'
  get 'rankings/review', to: 'rankings#review'
  
  resources :reviews, only: [:create, :destroy]
  
  resources :my_conditions do
    get 'cities_select', on: :collection
  end

end

app/models/ownership.rb
class Ownership < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @book = Book.find_or_initialize_by(isbn: params[:isbn])

    unless @book.persisted?
      # @book が保存されていない場合、先に @book を保存する
      results = RakutenWebService::Books::Book.search(isbn: @book.isbn)

      @book = Book.new(read(results.first))
      @book.save
    end

    # Want 関係として保存
    if params[:type] == 'Want'
      current_user.want(@book)
      flash[:success] = '欲しい！に追加 しました。'
    elsif params[:type] == 'Have'
      current_user.have(@book)
      flash[:success] = '持ってる！に追加 しました。'
    end

    redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])

    if params[:type] == 'Want'
      current_user.unwant(@book) 
      flash[:success] = '欲しい！ を解除しました。'
    elsif params[:type] == 'Have'
      current_user.unhave(@book) 
      flash[:success] = '持ってる！を解除しました。'
    end

    redirect_back(fallback_location: root_path)
  end
end

app/views/ownerships/_have_button.html.erb
<% if current_user && current_user.have?(book) %>
  <%= form_tag(ownership_path(book.id), method: :delete) do %>
    <%= hidden_field_tag :book_id, book.id %>
    <%= hidden_field_tag :type, 'Have' %>
    <%= submit_tag '持ってる！解除', class: 'btn btn-success btn-sm' %>
  <% end %>
<% else %>
  <%= form_tag(ownerships_path) do %>
    <%= hidden_field_tag :isbn, book.isbn %>
    <%= hidden_field_tag :type, 'Have' %>
    <%= submit_tag '持ってる！', class: 'btn btn-primary btn-sm' %>
  <% end %>
<% end %>

app/views/ownerships/_want_button.html.erb
<% if current_user && current_user.want?(book) %>
  <%= form_tag(ownership_path(book.id), method: :delete) do %>
    <%= hidden_field_tag :book_id, book.id %>
    <%= hidden_field_tag :type, 'Want' %>
    <%= submit_tag '欲しい！解除', class: 'btn btn-success btn-sm' %>
  <% end %>
<% else %>
  <%= form_tag(ownerships_path) do %>
    <%= hidden_field_tag :isbn, book.isbn %>
    <%= hidden_field_tag :type, 'Want' %>
    <%= submit_tag '欲しい！', class: 'btn btn-primary btn-sm' %>
  <% end %>
<% end %>